### ISSUE TITLE
covid-19: SmiNet reporting, KeyError: name

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#157]
```2020-06-02 17:21:12,185 - clarity_ext.cli - ERROR - Exception while running extension
Traceback (most recent call last):
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/cli.py", line 127, in extension
    extension_svc.run_exec(config, args, module)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 102, in run_exec
    self._run(config, path, pid, module, False, False)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 268, in _run
    instance.execute()
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 128, in execute
    self.report(substance)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 88, in report
    sample_free_text="Anamnes: Personalprov")
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 125, in export_to_sminet
    patient = self.create_patient(provider)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 106, in create_patient
    patient_name(),
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 92, in patient_name
    name = provider.patient["name"]
KeyError: 'name'
```

**Comment by boulund** [comment]
Ok, case of protected identity. 

We will have to make the code handle this.

**Comment by boulund** [comment]
Merged to dev, then prod.
