### ISSUE TITLE
covid-19: report to sminet fails

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#177]
from prod:

```
61853 2020-06-25 23:00:31,717 - clarity_ext.cli - ERROR - Exception while running extension
61854 Traceback (most recent call last):
61855   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/cli.py", line 127, in extension
61856     extension_svc.run_exec(config, args, module)
61857   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 102, in run_exec
61858     self._run(config, path, pid, module, False, False)
61859   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 268, in _run
61860     instance.execute()
61861   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 129, in execute
61862     self.report(substance)
61863   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 89, in report
61864     service_request_notes_to_append={"order_note"})
61865   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 154, in export_to_sminet
61866     sample_free_text_with_notes = self._append_service_request_notes(sample_free_text, provider, service_request_notes_to_append)
61867   File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 130, in _append_service_request_notes
61868     note_key, note_value = note["text"].split("=", 1)
61869 TypeError: string indices must be integers
```

https://github.com/ctmrbio/claritylims/blob/prod/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py#L131

Easy fix: add `TypeError` to the list of handled exceptions.

**Comment by boulund** [comment]
Jonas reports this as being fixed.
