### ISSUE TITLE
covid-19: Reporting KUL samples to SmiNet fails

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#182]
```
2020-07-06 16:20:26,031 - clarity_ext.extensions - INFO - Running extension clarity_ext_scripts.covid.report_to_sminet for pid=24-292322, test_mode=False
2020-07-06 16:20:26,031 - clarity_ext.extensions - INFO -  - Path=/opt/gls/clarity/automation_worker/node/temp/epp-06072020-452267503647292312.24-292322
2020-07-06 16:20:26,137 - clarity_ext.extensions - INFO - Executing at /opt/gls/clarity/automation_worker/node/temp/epp-06072020-452267503647292312.24-292322
2020-07-06 16:20:26,901 - clarity_ext.cli - ERROR - Exception while running extension
Traceback (most recent call last):
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/cli.py", line 127, in extension
    extension_svc.run_exec(config, args, module)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 102, in run_exec
    self._run(config, path, pid, module, False, False)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 268, in _run
    instance.execute()
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 129, in execute
    self.report(substance)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/report_to_sminet.py", line 89, in report
    service_request_notes_to_append={"order_note"})
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 159, in export_to_sminet
    referring_clinic = self.create_referring_clinic(provider)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_sminet_service.py", line 54, in create_referring_clinic
    referring_doctor = provider.service_request["resource"]["requester"]["display"]
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by boulund** [comment]
Waiting for access to direkttest DB to verify the data stored for these samples, so we can figure out what is actually wrong here.

**Comment by boulund** [comment]
It seems this is due to a responsible medical person not being assigned in Direkttests system. The API now renders a `null` in place of the missing data, which is probably incorrect. Jonas will fix this for us, hopefully later this week. Either by rendering something else (e.g. an empty string), or by removing the field in the API response entirely (which probably means we will have to fix our code to handle that situation.

**Comment by boulund** [comment]
Solution:

We fill in requester info for all subregions in direkttest's system. Will require us to wait until that is fixed before we have final validation of no-report to sminet for KUL samples.

**Comment by boulund** [comment]
This is now validated and works well
