### ISSUE TITLE
'Connection aborted.', BadStatusLine('No status line received - the server has closed the connection'

### ISSUE THREAD

**Issue by boulund** [ctmrbio/claritylims#273]
This issue keeps popping up more frequently recently:

```
2020-11-26 09:50:22,581 - clarity_ext.extensions - INFO - Running extension clarity_ext_scripts.covid.review_update_local for pid=24-1261984, test_mode=False
2020-11-26 09:50:22,581 - clarity_ext.extensions - INFO -  - Path=/opt/gls/clarity/automation_worker/node/temp/epp-26112020-4332980017590046098.24-1261984
2020-11-26 09:50:22,586 - clarity_ext.extensions - INFO - Executing at /opt/gls/clarity/automation_worker/node/temp/epp-26112020-4332980017590046098.24-1261984
2020-11-26 09:50:36,561 - clarity_ext.cli - ERROR - Exception while running extension
Traceback (most recent call last):
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/cli.py", line 127, in extension
    extension_svc.run_exec(config, args, module)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 102, in run_exec
    self._run(config, path, pid, module, False, False)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/extensions.py", line 268, in _run
    instance.execute()
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/import_samples.py", line 186, in execute
    biobank_barcode_by_sample_referal_code=barcode_by_sample)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/import_samples.py", line 126, in create_in_mem_container
    service_request_id)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/import_samples.py", line 41, in create_sample
    referring_clinic_name = provider.patient["managingOrganization"]["display"].encode("ascii", "ignore")
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/repos/clarity-ext/clarity_ext/utils.py", line 16, in _lazyprop
    setattr(self, attr_name, fn(self))
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/services/knm_service.py", line 79, in patient
    return self.client.get_by_reference(self.patient_ref)
  File "/opt/gls/clarity/users/glsai/deployment/claritylims/clarity-ext-scripts/clarity_ext_scripts/covid/partner_api_client.py", line 477, in get_by_reference
    response = self._session.get(url=url, headers=headers)
  File "/opt/gls/clarity/users/glsai/.conda/envs/clarity-ext/lib/python2.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/opt/gls/clarity/users/glsai/.conda/envs/clarity-ext/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/gls/clarity/users/glsai/.conda/envs/clarity-ext/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/gls/clarity/users/glsai/.conda/envs/clarity-ext/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
```

**Comment by boulund** [comment]
Fixed in #279
